from __future__ import annotations

import numpy as np
from scipy.signal import find_peaks

SAMPLING_RATE = 100

HEADLINES: dict[str, str] = {
    "NORM": "Normal Sinus Rhythm",
    "MI": "Signs of Myocardial Infarction Detected",
    "STTC": "ST-Segment and T-Wave Abnormalities Detected",
    "CD": "Conduction Disturbance Detected",
    "HYP": "Cardiac Hypertrophy Indicators Detected",
}

SUMMARIES: dict[str, str] = {
    "NORM": (
        "No significant arrhythmia detected. Rate and rhythm appear regular with "
        "normal P-wave, QRS, and T-wave morphology across all leads."
    ),
    "MI": (
        "Abnormal Q-waves and ST-segment changes consistent with prior or evolving "
        "myocardial infarction. The model concentrated on the early QRS complex and "
        "ST segment — the hallmark regions for ischaemic injury."
    ),
    "STTC": (
        "ST-segment depression or T-wave inversion detected across multiple leads. "
        "These changes may reflect ischaemia, electrolyte disturbance, or medication "
        "effects and warrant clinical correlation."
    ),
    "CD": (
        "Prolonged or aberrant QRS morphology detected, consistent with bundle branch "
        "block or intraventricular conduction delay. The model's attention spans the "
        "full QRS width, reflecting sensitivity to its temporal extent."
    ),
    "HYP": (
        "Voltage criteria and repolarisation changes consistent with left or right "
        "ventricular hypertrophy. The model highlighted the R-wave and S-wave peaks — "
        "the primary amplitude-based diagnostic features."
    ),
}

REGION_LABELS: dict[str, list[str]] = {
    "NORM": [],
    "MI": ["Q-wave region", "ST segment"],
    "STTC": ["ST-T region"],
    "CD": ["QRS complex"],
    "HYP": ["R-wave peak"],
}

DISCLAIMER = (
    "This output is generated by a research model trained on the PTB-XL dataset. "
    "It is not validated for clinical use and must not be used for diagnosis or "
    "treatment decisions."
)


def _flagged_regions(
    cam: list[float],
    class_name: str,
    sr: int = SAMPLING_RATE,
) -> list[dict]:
    labels = REGION_LABELS.get(class_name, [])
    if not labels or not cam:
        return []

    arr = np.array(cam, dtype=np.float32)
    peaks, _ = find_peaks(arr, height=0.45, distance=25)

    regions = []
    for i, peak in enumerate(peaks[: len(labels)]):
        half = 15
        start = max(0, peak - half)
        end = min(len(arr) - 1, peak + half)
        regions.append(
            {
                "label": labels[i],
                "start_s": round(int(start) / sr, 3),
                "end_s": round(int(end) / sr, 3),
                "peak_s": round(int(peak) / sr, 3),
            }
        )

    return regions


def generate_report(
    predicted_class: str,
    confidence: float,
    cam: list[float] | None = None,
) -> dict:
    return {
        "headline": HEADLINES[predicted_class],
        "summary": SUMMARIES[predicted_class],
        "confidence_pct": round(confidence * 100, 1),
        "flagged_regions": _flagged_regions(cam or [], predicted_class),
        "disclaimer": DISCLAIMER,
    }
